SimpleTaskManagerApp/SimpleTaskManagerApp/Areas/Administrator/Controllers/LogsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleTaskManagerApp.Data;
using SimpleTaskManagerApp.Services.Data.Interfaces;
using SimpleTaskManagerApp.ViewModels.Administrator;
using SimpleTaskManagerApp.ViewModels.LogEntry;

namespace SimpleTaskManagerApp.Areas.Administrator.Controllers
{
	[Area("Administrator")]
	[Authorize(Roles = "Administrator")]
	public class LogsController : Controller
	{
		private readonly TaskManagerDbContext _context;
		private readonly ILogEntryService _logEntryService;
        public LogsController(TaskManagerDbContext context, ILogEntryService logEntryService)
        {
            this._context = context;
			this._logEntryService = logEntryService;
        }
        public async Task<IActionResult> Index(int page = 1,int pageSize = 100)
		{
			int totalLogs = await _context.LogEntries.CountAsync();
			int totalPages = (int)Math.Ceiling(totalLogs / (double)pageSize);

			IEnumerable<LogEntryViewModel> logs = await _logEntryService.GetLogsAsync(page,pageSize);

			AdminLogEntryListViewModel model = new AdminLogEntryListViewModel
			{
				Logs = logs,
				CurrentPage = page,
				TotalPages = totalPages
			};

			return View(model);
		}
	}
}

SimpleTaskManagerApp/SimpleTaskManagerApp/Areas/Administrator/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleTaskManagerApp.Controllers;
using SimpleTaskManagerApp.Services.Data.Interfaces;
using SimpleTaskManagerApp.ViewModels.Administrator;
using static SimpleTaskManagerApp.Common.Utility;

namespace SimpleTaskManagerApp.Areas.Administrator.Controllers
{
	[Area("Administrator")]
	[Authorize(Roles = "Administrator")]
	public class UsersController : BaseController
	{
		private readonly IAdministratorService _administratorService;

		public UsersController(IAdministratorService administratorService)
		{
			this._administratorService = administratorService;
		}

		[HttpGet]
		public async Task<IActionResult> Index(FilterUserViewModelAdmin filter)
		{	
			CheckPages(filter.PageNumber, filter.PageSize);

			var users = await _administratorService.GetFilteredUsersAsync(filter);
			int totalCount = await _administratorService.GetFilteredUsersCountAsync(filter);

			var model = new AdminUsersIndexViewModel
			{
				Users = users,
				Filter = filter,
				CurrentPage = filter.PageNumber,
				TotalPages = (int)Math.Ceiling(totalCount / (double)filter.PageSize)
			};

			return View(model);
		}

		[HttpPost]
		[AutoValidateAntiforgeryToken]
		public async Task<IActionResult> MakeAdmin(string id)
		{
			string? currentUserId = GetCurrentUserId();

			bool result = await _administratorService.PromoteToAdminAsync(id, currentUserId);

			if (result)
			{
				TempData["Success"] = "User promoted to Administrator.";
			}
			else
			{
				TempData["Error"] = "Could not promote user.";
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		[AutoValidateAntiforgeryToken]
		public async Task<IActionResult> RemoveAdmin(string id)
		{
			string? currentUserId = GetCurrentUserId();

			bool result = await _administratorService.DemoteFromAdminAsync(id, currentUserId);

			if (result)
			{
				TempData["Success"] = "User demoted from Administrator.";
			}
			else
			{
				TempData["Error"] = "Could not demote user.";
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(string id)
		{

			Guid userId = Guid.Empty;
			bool isUserValid = IsGuidValid(id, ref userId);

			if (!isUserValid)
			{
				return NotFound();
			}

			bool result = await _administratorService.RemoveUserAsync(id);

			if (!result)
			{
				return NotFound();
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> LockUser(string id)
		{
			Guid userId = Guid.Empty;
			bool isUserValid = IsGuidValid(id, ref userId);

			if (!isUserValid)
			{
				return NotFound();
			}

			bool result = await _administratorService.LockOnUserAsync(id);

			if (!result)
			{
				return NotFound();
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> UnlockUser(string id)
		{
			Guid userId = Guid.Empty;
			bool isUserValid = IsGuidValid(id, ref userId);

			if (!isUserValid)
			{
				return NotFound();
			}

			bool result = await _administratorService.UnlockUserAsync(id);

			if (!result)
			{
				return NotFound();
			}

			return RedirectToAction(nameof(Index));
		}
	}
}

SimpleTaskManagerApp/SimpleTaskManagerApp/Controllers/TasksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SimpleTaskManagerApp.Data;
using SimpleTaskManagerApp.Services.Data.Interfaces;
using SimpleTaskManagerApp.ViewModels.AppTask;
using SimpleTaskManagerApp.ViewModels.Status;
using static SimpleTaskManagerApp.Common.Utility;

namespace SimpleTaskManagerApp.Controllers
{
	public class TasksController : BaseController
	{
		private readonly IAppTaskService _appTaskService;
		private readonly IStatusService _statusService;
		private readonly TaskManagerDbContext _context;
		private readonly IUrgencyLevelService _urgencyLevelService;
		public TasksController(IAppTaskService appTaskService, IStatusService statusService, TaskManagerDbContext context, IUrgencyLevelService urgencyLevelService)
        {
            _appTaskService = appTaskService;
			_statusService = statusService;
			_context = context;
			_urgencyLevelService = urgencyLevelService;
        }

		[HttpGet]
		public async Task<IActionResult> Index(FilterAppTaskViewModelUser filter)
		{
			string? userId = GetCurrentUserId();

			if (!Guid.TryParse(userId, out Guid userGuid))
			{
				return NotFound();
			}

			CheckPages(filter.PageSize, filter.PageNumber);

			bool isAdmin = User.IsInRole("Administrator");

			int totalTaskCount = await _appTaskService.GetFilteredTasksCountAsync(userId, filter, isAdmin);

			IEnumerable<AppTaskViewModel> tasks = await _appTaskService.GetFilteredTasksAsync(userId, filter, isAdmin);

			IEnumerable<StatusViewModel> statuses = await _statusService.GetAllStatusesAsync();

			IEnumerable<SelectListItem> statusSelectList = statuses.Select(s => new SelectListItem
			{
				Value = s.Id.ToString(),
				Text = s.Name
			});

			var urgencyLevels = await _context.UrgencyLevels.Select(u => new SelectListItem
			{
				Value = u.Id.ToString(),
				Text = u.Name
			})
				.ToListAsync();

			UserTasksIndexViewModel model = new UserTasksIndexViewModel
			{
				Filter = filter,
				Statuses = statusSelectList,
				Tasks = tasks,
				CurrentPage = filter.PageNumber,
				UrgencyLevels = urgencyLevels,
				TotalPages = (int)Math.Ceiling(totalTaskCount / (double)filter.PageSize)
			};

			return View(model);
		}

		[HttpGet]
		[Authorize]
		public async Task<IActionResult> Create()
		{
			AppTaskCreateViewModel model = await _appTaskService.GetCreateViewModelAsync();
			return View(model);
		}

		[HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(AppTaskCreateViewModel model)
		{
			if (!ModelState.IsValid)
			{
				model.Statuses = (await _appTaskService.GetCreateViewModelAsync()).Statuses;
				model.UrgencyLevels = (await _appTaskService.GetCreateViewModelAsync()).UrgencyLevels;
				return View(model);
			}

			string? userId = GetCurrentUserId();
			await _appTaskService.CreateAsync(model, userId);

			return RedirectToAction(nameof(Index));
		}


		//GET CreatePartial
		[HttpGet]
		[Authorize]
		public async Task<IActionResult> CreatePartial()
		{
			AppTaskCreateViewModel model = new AppTaskCreateViewModel
			{
				Statuses = (await _appTaskService.GetCreateViewModelAsync()).Statuses,
				UrgencyLevels = await _urgencyLevelService.GetAllUrgencyLevelsAsync()
			};


			return PartialView("_CreatePartial", model);
		}

		//POST CreatePartial
		[HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreatePartial(AppTaskCreateViewModel model)
		{
			if (!ModelState.IsValid)
			{

				model.Statuses = (IEnumerable<AppTaskStatusViewModel>)await _statusService.GetAllStatusesAsync();
				model.UrgencyLevels = await _urgencyLevelService.GetAllUrgencyLevelsAsync();

				return PartialView("_CreatePartial", model);
			}

			await _appTaskService.CreateAsync(model, GetCurrentUserId());
			return Ok(); 
		}

		//GET EditPartial
		[HttpGet]
		[Authorize]
		public async Task<IActionResult> EditPartial(string? id)
		{

			Guid taskGuid = Guid.Empty;
			bool isTaskGuidValid = IsGuidValid(id,ref taskGuid);

			if (!isTaskGuidValid)
			{

				//return RedirectToAction("Custom404","Error");
				return NotFound();
			}

			string? userId = GetCurrentUserId();
			Guid userGuid = Guid.Empty;
			bool isUserValid = IsGuidValid(userId,ref userGuid);

			if (!isUserValid)
			{
				
				//return RedirectToAction("Custom404","Error");
				return NotFound();
			}

			bool isAdmin = User.IsInRole("Administrator");

			EditTaskViewModel? model = await _appTaskService.GetEditViewModelAsync(taskGuid, userGuid, isAdmin);

			if (model == null) 
			{
				return NotFound();
			}
			
			return PartialView("_EditPartial",model);
		}

		//POST EditPartial
		[HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> EditPartial(EditTaskViewModel model)
		{
			if (!ModelState.IsValid) 
			{
				model.Statuses = (IEnumerable<AppTaskStatusViewModel>)await _statusService.GetAllStatusesAsync();
				model.UrgencyLevels = await _urgencyLevelService.GetAllUrgencyLevelsAsync();

				return PartialView("_EditPartial", model);
			}

			Guid taskGuid = Guid.Empty;
			bool isTaskValid = IsGuidValid(model.Id.ToString(), ref taskGuid);

			if (!isTaskValid)
			{
				return NotFound();
			}

			string? userId = GetCurrentUserId();
			Guid userGuid = Guid.Empty;
			bool isUserValid = IsGuidValid(userId, ref userGuid);

			if (!isUserValid)
			{
				return NotFound();
			}

			bool isAdmin = User.IsInRole("Administrator");

			var result = await this._appTaskService.PostEditViewModelAsync(taskGuid, userGuid, isAdmin, model);

			if (!result)
			{
				return BadRequest();
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpPost("Tasks/Delete/{taskId}")]
		[Authorize]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(Guid taskId)
		{
			string? userId = GetCurrentUserId();
			Guid userGuid = Guid.Empty;
			bool isUserValid = IsGuidValid(userId, ref userGuid);

			if (!isUserValid) 
			{
				return NotFound();
			}

			bool isAdmin = User.IsInRole("Administrator");

			bool isDeleted = await this._appTaskService.PostDeleteViewModelAsync(taskId, userGuid, isAdmin);

			if (!isDeleted)
			{
				return BadRequest("Unable to delete task.");
			}

			return Ok();
		}

		[HttpGet]
		[Authorize]
		public async Task<IActionResult> DetailsPartial(string? id)
		{
			string? userId = GetCurrentUserId();
			Guid userGuid = Guid.Empty;
			bool isUserValid = IsGuidValid(userId, ref userGuid);

			if (!isUserValid)
			{
				return NotFound();
			}

			Guid taskGuid = Guid.Empty;
			bool isTaskValid = IsGuidValid(id, ref taskGuid);

			if (!isTaskValid)
			{
				return NotFound();
			}

			bool isAdmin = User.IsInRole("Administrator");

			var model = await this._appTaskService.GetDetailsViewModelAsync(taskGuid, userGuid, isAdmin);

			if (model == null)
			{
				return NotFound();
			}

			return PartialView("_DetailsPartial", model);
		}
	}
}

SimpleTaskManagerApp/SimpleTaskManagerApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Admin Panel - SimpleTaskManagerApp</title>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-KZC0...F4g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

	<!-- Flatpickr -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
	<link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_green.css">

	<!-- Bootstrap Icons -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

	<link rel="stylesheet" href="~/SimpleTaskManagerApp.styles.css" asp-append-version="true" />
	<script src="~/js/site.tasks.js" asp-append-version="true"></script>
</head>

<body class="d-flex flex-column min-vh-100">
	@Html.AntiForgeryToken()

	<header>
		<nav class="navbar navbar-expand-lg" style="background-color: #2F3E6E;">
			<div class="container-fluid">
				<a class="navbar-brand fw-bold text-white" asp-area="" asp-controller="Home" asp-action="Index">
					SimpleTaskManagerApp
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#adminNavbar" aria-controls="adminNavbar" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="adminNavbar">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">

						<li class="nav-item">
							<a class="nav-link text-white" asp-controller="Tasks" asp-action="Index">
								<i class="fas fa-list-check me-1"></i>All Tasks
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="Tasks" asp-action="Create">
								<i class="fas fa-plus-circle me-1"></i>Create Task
							</a>
						</li>
						@if (User.IsInRole("Administrator"))
						{
							<li class="nav-item">
								<a class="nav-link text-white" asp-area="Administrator" asp-controller="Administrator" asp-action="Index">
									<i class="fas fa-home me-1"></i>Dashboard
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link text-white" asp-area="Administrator" asp-controller="Users" asp-action="Index">
									<i class="fas fa-users-cog me-1"></i>User Management
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-white" asp-area="Administrator" asp-controller="Logs" asp-action="Index">
									<i class="fas fa-file-alt me-1"></i>Logs
								</a>
							</li>
						}			
					</ul>

					<ul class="navbar-nav">
						<li class="nav-item">
							<partial name="_LoginPartial" />
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<main role="main" class="flex-fill pb-3">
		<div class="container-fluid mt-4">
			@RenderBody()
		</div>
	</main>

	<footer class="text-white py-3" style="background-color: #2F3E6E;">
		<div class="container text-center small">
			<div class="mb-2">
				&copy; 2025 SimpleTaskManagerApp
			</div>
			<div>
				<a class="text-white text-decoration-none me-3" asp-action="Privacy">Privacy</a>
				<a class="text-white text-decoration-none me-3" asp-action="Terms">Terms</a>
				<a class="text-white text-decoration-none" asp-action="Contacts">Contacts</a>
			</div>
		</div>
	</footer>

	<!-- JS dependencies -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>